# Generated by Django 2.0.6 on 2018-06-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180615_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Can set book as returned'), ('can_renew_books', 'Can renew books'))},
        ),
    ]
